[env:native]
platform = native
build_flags = -std=c++17 -O2 -Wall -Wextra -Isrc
build_src_filter = +<core/> +<host/>
test_framework = unity
test_build_src = yes

[env:cyd]
platform = espressif32
board = esp32dev
framework = arduino
upload_speed = 921600
monitor_speed = 115200
board_build.partitions = huge_app.csv
build_flags = -std=gnu++17 -Isrc
build_src_filter = +<core/> +<device/>
lib_deps = bodmer/TFT_eSPI@^2.5.43
