#!/usr/bin/env python3
"""Extract the 5x7 GLCD font from TFT_eSPI into a core/ header.

The source is a flat array of 5-byte glyphs, column-major, bit 0 = top row.
We keep only ASCII 32..126, which is everything the UI draws.
"""
import re
import sys
from pathlib import Path

SRC = Path(".pio/libdeps/cyd/TFT_eSPI/Fonts/glcdfont.c")
OUT = Path("src/core/font_data.h")
FIRST, LAST = 32, 126

def main() -> int:
    if not SRC.exists():
        print(f"missing {SRC}; run: pio pkg install -e cyd", file=sys.stderr)
        return 1
    text = SRC.read_text(errors="replace")
    body = text[text.index("{") + 1 : text.rindex("}")]
    # Strip comments before tokenizing to avoid picking up numbers from comments
    body = re.sub(r"//.*?$", "", body, flags=re.MULTILINE)  # Remove // to end-of-line
    body = re.sub(r"/\*.*?\*/", "", body, flags=re.DOTALL)  # Remove /* */ blocks
    vals = [int(t, 0) for t in re.findall(r"0[xX][0-9a-fA-F]+|\d+", body)]
    if len(vals) < (LAST + 1) * 5:
        print(f"expected >= {(LAST+1)*5} bytes, got {len(vals)}", file=sys.stderr)
        return 1
    glyphs = vals[FIRST * 5 : (LAST + 1) * 5]
    lines = [
        "// Generated by tools/extract_font.py -- do not edit.",
        "// Adafruit GLCD 5x7 font, ASCII 32..126, column-major, bit 0 = top row.",
        "#pragma once",
        "#include <stdint.h>",
        "namespace cb {",
        f"constexpr char FONT_FIRST = {FIRST};",
        f"constexpr char FONT_LAST = {LAST};",
        "constexpr uint8_t FONT_DATA[] = {",
    ]
    for i in range(0, len(glyphs), 5):
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in glyphs[i : i + 5]) + ",")
    lines += ["};", "}  // namespace cb", ""]
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT} ({len(glyphs)} bytes, {len(glyphs)//5} glyphs)")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
