#!/usr/bin/env python3
"""Rasterise a TTF into src/core/font_data.h as a fixed-cell bitmap font.

Replaces the Adafruit GLCD 5x7 that tools/extract_font.py pulls out of
TFT_eSPI. That font is thin and generic; the Pip-Boy look wants something
tall and squared.

Ubuntu Mono Bold at 13px measures 7x11 with a 7px advance. Seven is the
ceiling: the footer draws a 26-character caption and a 16-character
staleness annotation on one 308px line, so 42*ADV + 6 <= 308.

Emits ROW-major glyphs, one byte per row, bit 0 = leftmost. The old header
was column-major with one byte per column, which caps height at 8.

Run:  uv run --with pillow python tools/make_font.py
"""
from PIL import Image, ImageDraw, ImageFont
PATH="/Users/dannon/Library/Fonts/UbuntuMono-Bold.ttf"; PX=13
FIRST,LAST = 32,126
W,H = 7,11
f = ImageFont.truetype(PATH, PX)
# find the y offset that puts caps flush at the top of the cell
probe = Image.new('L',(40,40),0); ImageDraw.Draw(probe).text((5,5),"AXZ0",font=f,fill=255)
bb = probe.point(lambda v:255 if v>110 else 0).getbbox()
top = bb[1]-5
rows=[]
for code in range(FIRST,LAST+1):
    img=Image.new('L',(W+8,H+16),0); d=ImageDraw.Draw(img)
    d.text((0,-top),chr(code),font=f,fill=255)
    bm=img.point(lambda v:255 if v>110 else 0)
    glyph=[]
    for y in range(H):
        bits=0
        for x in range(W):
            if bm.getpixel((x,y)): bits |= (1<<x)
        glyph.append(bits)
    rows.append((code,glyph))
out=["// Generated by tools/make_font.py -- do not edit.",
     "// Ubuntu Mono Bold rasterised at 13px: 7x11 cell, row-major, bit 0 = leftmost.",
     "#pragma once","#include <stdint.h>","namespace cb {",
     f"constexpr char FONT_FIRST = {FIRST};",f"constexpr char FONT_LAST = {LAST};",
     "constexpr uint8_t FONT_DATA[] = {"]
for code,g in rows:
    # The character is quoted and the code point printed after it: a bare
    # trailing backslash in a // comment is a line continuation, and it ate
    # the next glyph's row silently -- ']' rendered as '^' for a while.
    out.append("    "+", ".join(f"0x{b:02X}" for b in g)+f",   // '{chr(code)}' {code}")
out += ["};","}  // namespace cb",""]
open('src/core/font_data.h','w').write("\n".join(out))
print("cells", len(rows), "bytes", len(rows)*H, "top-offset", top)
