#!/usr/bin/env python3
"""Rasterise Ubuntu Mono Bold into the two bitmap fonts in src/core/.

Replaces the Adafruit GLCD 5x7 that tools/extract_font.py pulls out of
TFT_eSPI. That font is thin and generic; the Pip-Boy look wants something
tall and squared.

TWO fonts, cut at the two sizes actually drawn, rather than one cut small and
doubled. Doubling turns every glyph pixel into a 2x2 block, which on the panel
reads as exactly what it is -- a low-resolution font stretched -- and it was
the last thing on the screen that still looked wrong.

  small  13px source -> 7x11 cell, 7px advance, one uint8_t per row
  big    25px source -> 13x20 cell, 13px advance, one uint16_t per row

Seven is the ceiling for the small advance: the footer draws a 26-character
caption and a 16-character staleness annotation on one 308px line, so
42*ADV + 6 <= 308. Thirteen is what the big one needs to keep "AP SESSION" and
a right-aligned "100%" clear of each other inside HERO_W. 25px rather than 26
for the big one: 26 draws ink into all thirteen columns, so adjacent glyphs
touch and the advance has to grow to 14 to make a gap.

Emits ROW-major glyphs, bit 0 = leftmost. The header this replaced was
column-major with one byte per column, which caps a cell at eight rows.

Run:  uv run --with pillow python tools/make_font.py
"""
from PIL import Image, ImageDraw, ImageFont

PATH = "/Users/dannon/Library/Fonts/UbuntuMono-Bold.ttf"
FIRST, LAST = 32, 126

def raster(px, w, h):
    f = ImageFont.truetype(PATH, px)
    # The y offset that puts capitals flush with the top of the cell. Measured
    # rather than taken from the font's ascent, which includes accent room no
    # glyph here uses and would waste two rows at the top of every cell.
    probe = Image.new('L', (px * 4, px * 4), 0)
    ImageDraw.Draw(probe).text((5, 5), "AXZ0", font=f, fill=255)
    top = probe.point(lambda v: 255 if v > 110 else 0).getbbox()[1] - 5
    out = []
    for code in range(FIRST, LAST + 1):
        img = Image.new('L', (w + px, h + px * 2), 0)
        ImageDraw.Draw(img).text((0, -top), chr(code), font=f, fill=255)
        bm = img.point(lambda v: 255 if v > 110 else 0)
        glyph = []
        for y in range(h):
            bits = 0
            for x in range(w):
                if bm.getpixel((x, y)): bits |= (1 << x)
            glyph.append(bits)
        out.append((code, glyph))
    return out

def emit(path, rows, name, ctype, digits, w, h, px):
    out = ["// Generated by tools/make_font.py -- do not edit.",
           f"// Ubuntu Mono Bold rasterised at {px}px: {w}x{h} cell, row-major, bit 0 = leftmost.",
           "#pragma once", "#include <stdint.h>", "namespace cb {"]
    if name == "FONT_DATA":
        out += [f"constexpr char FONT_FIRST = {FIRST};", f"constexpr char FONT_LAST = {LAST};"]
    out.append(f"constexpr {ctype} {name}[] = {{")
    for code, g in rows:
        # The character is quoted and the code point printed after it: a bare
        # trailing backslash in a // comment is a line continuation, and it ate
        # the next glyph's row silently -- ']' rendered as '^' for a while.
        out.append("    " + ", ".join(f"0x{b:0{digits}X}" for b in g) + f",   // '{chr(code)}' {code}")
    out += ["};", "}  // namespace cb", ""]
    open(path, 'w').write("\n".join(out))
    used = max((y for _, g in rows for y, b in enumerate(g) if b), default=-1) + 1
    cols = max((x for _, g in rows for b in g for x in range(w) if b >> x & 1), default=-1) + 1
    print(f"{path}: {len(rows)} cells, {len(rows) * h * (digits // 2)} bytes, "
          f"rows used {used}/{h}, cols used {cols}/{w}")

emit('src/core/font_data.h', raster(13, 7, 11), 'FONT_DATA', 'uint8_t', 2, 7, 11, 13)
emit('src/core/font_big_data.h', raster(25, 13, 20), 'FONT_BIG_DATA', 'uint16_t', 4, 13, 20, 25)
