#!/usr/bin/env python3
"""Convert the two Spleen BDFs into the bitmap fonts in src/core/.

  small  spleen-6x12   -> 6x12 cell, 6px advance, one uint8_t per row
  big    spleen-12x24  -> 12x24 cell, 12px advance, one uint16_t per row

This used to rasterise Ubuntu Mono Bold with PIL. Downscaling a TTF to an
eight-row cap height means thresholding antialiased edges, and the glyphs come
out lopsided -- 'A' landed as ..##... / ..###.. / ..#.#.. , which is a
different shape on each side of its own apex. On the panel that reads as
blurry, and it is not the bloom: it is the letterforms. Spleen is drawn bead
by bead at these exact sizes, so the forms are symmetric and deliberate, the
stems are a whole pixel, and the counters stay open under bloom instead of
filling in. It is also BSD-2, and reading BDF needs no dependencies at all.

Seven was the ceiling on the small advance because the footer draws a
26-character caption and a 16-character annotation on one 308px line; six
clears it with room to spare.

Both faces keep their full BDF cell rather than being trimmed to the cap
height. The rows above the capitals are not empty -- brackets, braces and
quotes live up there, and the tab row draws [CLAUDE] in the small face.

Emits ROW-major glyphs, bit 0 = leftmost. BDF packs rows MSB-first and
left-aligned to a byte boundary, so every row is reversed on the way in.

Run:  python3 tools/make_font.py
"""
import os

HERE = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'assets', 'fonts')
FIRST, LAST = 32, 126

def read_bdf(path):
    fw = fh = fox = foy = 0
    glyphs, enc, bbx, bits = {}, None, None, None
    for line in open(path, encoding='latin-1'):
        t = line.split()
        if not t: continue
        if t[0] == 'FONTBOUNDINGBOX':
            fw, fh, fox, foy = (int(v) for v in t[1:5])
        elif t[0] == 'ENCODING': enc = int(t[1])
        elif t[0] == 'BBX': bbx = tuple(int(v) for v in t[1:5])
        elif t[0] == 'BITMAP': bits = []
        elif t[0] == 'ENDCHAR':
            if enc is not None and FIRST <= enc <= LAST and bbx is not None:
                w, h, xo, yo = bbx
                cell = [0] * fh
                for i, hexrow in enumerate(bits):
                    v = int(hexrow, 16) >> ((w + 7) // 8 * 8 - w)   # drop the pad
                    rev = 0
                    for b in range(w):
                        if v >> (w - 1 - b) & 1: rev |= 1 << b
                    # BDF measures y upward from the baseline; rows run top-down.
                    row = (fh + foy) - (yo + h) + i
                    if 0 <= row < fh: cell[row] |= rev << (xo - fox)
                glyphs[enc] = cell
            enc = bbx = bits = None
        elif bits is not None: bits.append(t[0])
    missing = [c for c in range(FIRST, LAST + 1) if c not in glyphs]
    if missing:
        raise SystemExit(f"{path}: no glyph for {missing}")
    return fw, fh, glyphs

def emit(path, src, name, ctype, digits):
    w, h, glyphs = read_bdf(os.path.join(HERE, src))
    out = ["// Generated by tools/make_font.py -- do not edit.",
           f"// {src}: {w}x{h} cell, row-major, bit 0 = leftmost.",
           "#pragma once", "#include <stdint.h>", "namespace cb {"]
    if name == "FONT_DATA":
        out += [f"constexpr char FONT_FIRST = {FIRST};", f"constexpr char FONT_LAST = {LAST};"]
    out.append(f"constexpr {ctype} {name}[] = {{")
    for code in range(FIRST, LAST + 1):
        # The character is quoted and the code point printed after it: a bare
        # trailing backslash in a // comment is a line continuation, and it ate
        # the next glyph's row silently -- ']' rendered as '^' for a while.
        out.append("    " + ", ".join(f"0x{b:0{digits}X}" for b in glyphs[code])
                   + f",   // '{chr(code)}' {code}")
    out += ["};", "}  // namespace cb", ""]
    open(path, 'w').write("\n".join(out))
    print(f"{path}: {LAST - FIRST + 1} cells, {w}x{h}, "
          f"{(LAST - FIRST + 1) * h * (digits // 2)} bytes")

emit('src/core/font_data.h', 'spleen-6x12.bdf', 'FONT_DATA', 'uint8_t', 2)
emit('src/core/font_big_data.h', 'spleen-12x24.bdf', 'FONT_BIG_DATA', 'uint16_t', 4)
